# Generated by Django 3.1.2 on 2020-11-05 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_email', models.CharField(max_length=50, verbose_name='Email')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('msg_date', models.DateTimeField(verbose_name='message_date')),
            ],
        ),
        migrations.CreateModel(
            name='TradeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, verbose_name='Символ')),
                ('description', models.TextField(max_length=500, verbose_name='Емітент цінних паперів')),
                ('exch', models.CharField(max_length=50, verbose_name='Біржа')),
                ('stock_type', models.CharField(max_length=50, verbose_name='Тип цінних паперів')),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Ціна відкриття')),
                ('high_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Найвища ціна')),
                ('low_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Найнижча ціна')),
                ('bid_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Ціна продажу')),
                ('ask_price', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Ціна купівлі')),
                ('change_percentage', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Зміна у відсотках')),
                ('prevclose', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Попередня ціна закриття')),
                ('week_52_high', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Найвижча ціна за рік')),
                ('week_52_low', models.DecimalField(decimal_places=5, max_digits=50, verbose_name='Найнижча ціна за рік')),
                ('trade_date', models.DateTimeField(verbose_name='Дата купівлі')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Біржовий аналітик')),
            ],
        ),
    ]
