# Generated by Django 3.1.2 on 2020-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='message_date'),
        ),
        migrations.AlterField(
            model_name='tradestock',
            name='trade_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата купівлі'),
        ),
    ]
